lib/todos_web/router.ex
defmodule TodosWeb.Router do
  use TodosWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TodosWeb do
    pipe_through :browser
    get "/", TodoController, :index

    resources "/todos", TodoController
    delete "/todo/clear_completed", TodoController, :clear_completed, as: :todo_clear_completed
    get "/todo/active", TodoController, :active, as: :active_todo
    get "/todo/completed", TodoController, :completed, as: :completed_todo
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodosWeb do
  #   pipe_through :api
  # end
end

lib/todos/application.ex
defmodule Todos.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Todos.Repo,
      # Start the endpoint when the application starts
      TodosWeb.Endpoint
      # Starts a worker by calling: Todos.Worker.start_link(arg)
      # {Todos.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Todos.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    TodosWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/todos/repo.ex
defmodule Todos.Repo do
  use Ecto.Repo,
    otp_app: :todos,
    adapter: Ecto.Adapters.Postgres
end

lib/todos/todo_list.ex
defmodule Todos.TodoList do
  @moduledoc """
  The TodoList context.
  """

  import Ecto.Query, warn: false
  alias Todos.Repo
  alias Todos.TodoList.Todo

  @doc """
  Returns the list of todos.

  ## Examples

      iex> list_todos()
      [%Todo{}, ...]

  """
  def list_todos do
    Todo |> order_by(asc: :id) |> Repo.all
  end

  def list_active_todos do
    from(t in Todo, where: t.completed == false) |> order_by(asc: :id) |> Repo.all
  end

  def list_completed_todos do
    from(t in Todo, where: t.completed) |> order_by(asc: :id) |> Repo.all
  end

  @doc """
  Gets a single todo.

  Raises `Ecto.NoResultsError` if the Todo does not exist.

  ## Examples

      iex> get_todo!(123)
      %Todo{}

      iex> get_todo!(456)
      ** (Ecto.NoResultsError)

  """
  def get_todo!(id), do: Repo.get!(Todo, id)

  @doc """
  Creates a todo.

  ## Examples

      iex> create_todo(%{field: value})
      {:ok, %Todo{}}

      iex> create_todo(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_todo(attrs \\ %{}) do
    %Todo{}
    |> Todo.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a todo.

  ## Examples

      iex> update_todo(todo, %{field: new_value})
      {:ok, %Todo{}}

      iex> update_todo(todo, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_todo(%Todo{} = todo, attrs) do
    todo
    |> Todo.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Todo.

  ## Examples

      iex> delete_todo(todo)
      {:ok, %Todo{}}

      iex> delete_todo(todo)
      {:error, %Ecto.Changeset{}}

  """
  def delete_todo(%Todo{} = todo) do
    Repo.delete(todo)
  end

  @doc """
  Deletes completed Todos

  ## Examples

      iex> delete_todo(todo)
      {:ok, %Todo{}}

      iex> delete_todo(todo)
      {:error, %Ecto.Changeset{}}

  """
  def clear_completed_todos do
    from(t in Todo, where: t.completed) |> Repo.delete_all
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking todo changes.

  ## Examples

      iex> change_todo(todo)
      %Ecto.Changeset{source: %Todo{}}

  """
  def change_todo(%Todo{} = todo) do
    Todo.changeset(todo, %{})
  end
end

lib/todos/todo_list/todo.ex
defmodule Todos.TodoList.Todo do
  use Ecto.Schema
  import Ecto.Changeset

  schema "todos" do
    field :completed, :boolean, default: false
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(todo, attrs) do
    todo
    |> cast(attrs, [:title, :completed])
    |> validate_required([:title, :completed])
  end
end

lib/todos_web/controllers/todo_controller.ex
defmodule TodosWeb.TodoController do
  use TodosWeb, :controller

  alias Todos.TodoList
  alias Todos.TodoList.Todo

  def index(conn, _params) do
    todos = TodoList.list_todos()
    changeset = TodoList.change_todo(%Todo{})
    completed_todos_count = Enum.count(TodoList.list_todos(), &(&1.completed))
    active_todos_count = Enum.count(TodoList.list_todos(), &(&1.completed == false))
    render(conn, "index.html", todos: todos, changeset: changeset,
      active_todos_count: active_todos_count, completed_todos_count: completed_todos_count)
  end

  def active(conn, _params) do
    todos = TodoList.list_active_todos()
    changeset = TodoList.change_todo(%Todo{})
    completed_todos_count = Enum.count(TodoList.list_todos(), &(&1.completed))
    active_todos_count = Enum.count(TodoList.list_todos(), &(&1.completed == false))
    render(conn, "index.html", todos: todos, changeset: changeset,
      active_todos_count: active_todos_count, completed_todos_count: completed_todos_count)
  end

  def completed(conn, _params) do
    todos = TodoList.list_completed_todos()
    changeset = TodoList.change_todo(%Todo{})
    completed_todos_count = Enum.count(TodoList.list_todos(), &(&1.completed))
    active_todos_count = Enum.count(TodoList.list_todos(), &(&1.completed == false))
    render(conn, "index.html", todos: todos, changeset: changeset,
      active_todos_count: active_todos_count, completed_todos_count: completed_todos_count)
  end

  def new(conn, _params) do
    changeset = TodoList.change_todo(%Todo{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"todo" => todo_params}) do
    case TodoList.create_todo(todo_params) do
      {:ok, todo} ->
        conn
        |> put_flash(:info, "Todo created successfully.")
        |> redirect(to: Routes.todo_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    todo = TodoList.get_todo!(id)
    render(conn, "show.html", todo: todo)
  end

  def edit(conn, %{"id" => id}) do
    todo = TodoList.get_todo!(id)
    changeset = TodoList.change_todo(todo)
    render(conn, "edit.html", todo: todo, changeset: changeset)
  end

  def update(conn, %{"id" => id, "todo" => todo_params}) do
    todo = TodoList.get_todo!(id)

    case TodoList.update_todo(todo, todo_params) do
      {:ok, todo} ->
        conn
        |> put_flash(:info, "Todo updated successfully.")
        |> redirect(to: Routes.todo_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", todo: todo, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    todo = TodoList.get_todo!(id)
    {:ok, _todo} = TodoList.delete_todo(todo)

    conn
    |> put_flash(:info, "Todo deleted successfully.")
    |> redirect(to: Routes.todo_path(conn, :index))
  end

  def clear_completed(conn, _params) do
    TodoList.clear_completed_todos
    todos = TodoList.list_todos()
    changeset = TodoList.change_todo(%Todo{})
    conn
    |> put_flash(:info, "Todos deleted successfully.")
    |> redirect(to: Routes.todo_path(conn, :index))
  end
end

lib/todos_web/views/todo_view.ex
defmodule TodosWeb.TodoView do
  use TodosWeb, :view

  def checked(todo) do
    if (todo.completed), do: "checked"
  end

  def clear_completed_style(completed_todos_count) do
    if (completed_todos_count == 0), do: "display: none;"
  end

  def completed_class(todo) do
    if (todo.completed), do: "completed"
  end

  def footer_style(active_todos_count) do
    if (active_todos_count == 0), do: "display: none;"
  end
end

lib/todos_web/templates/todo/edit.html.eex
<h1>Edit Todo</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.todo_path(@conn, :update, @todo)) %>

<span><%= link "Back", to: Routes.todo_path(@conn, :index) %></span>

lib/todos_web/templates/todo/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= text_input f, :title, class: 'new-todo', placeholder: "What needs to be done?", autofocus: 'autofocus' %>
<% end %>

lib/todos_web/templates/todo/index.html.eex
<header class="header">
  <h1>todos</h1>
  <%= render "form.html", Map.put(assigns, :action, Routes.todo_path(@conn, :create)) %>
</header>

<ul class="todo-list">
  <%= for todo <- @todos do %>
    <li class="<%= completed_class(todo) %>" ondblclick="this.className += ' editing'">
      <div class="view">
        <%= form_for @conn, Routes.todo_path(@conn, :update, todo), fn _f -> %>
          <input name="_method" type="hidden" value="put" />
          <input name="todo[completed]" type="hidden" value="false">
          <input name="todo[completed]" class="toggle" type="checkbox" value="true" <%= checked(todo) %> onchange="this.form.submit()">
          <label><%= todo.title %></label>
        <% end %>
        <%= button "", to: Routes.todo_path(@conn, :delete, todo), method: :delete, class: "destroy" %>
      </div>
      <div>
        <%= form_for @conn, Routes.todo_path(@conn, :update, todo), fn f -> %>
          <input name="_method" type="hidden" value="put" />
          <input name="todo[title]" class="edit" value="<%= todo.title %>" onblur="this.form.submit()">
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

<footer class="footer" style="<%= footer_style(@active_todos_count + @completed_todos_count) %>">
  <span class="todo-count">
  <strong><%= @active_todos_count %></strong>
  <%= Inflex.inflect("item", @active_todos_count) %> left
  </span>
  <ul class="filters">
    <li>
      <%= link "All", to: Routes.todo_path(@conn, :index) %>
    </li>
    <li>
      <%= link "Active", to: Routes.active_todo_path(@conn, :active) %>
    </li>
    <li>
      <%= link "Completed", to: Routes.completed_todo_path(@conn, :completed) %>
    </li>
  </ul>
  <%= button "Clear completed", to: Routes.todo_clear_completed_path(@conn, :clear_completed),
    method: :delete, class: "clear-completed", style: clear_completed_style(@completed_todos_count) %>
</footer>

lib/todos_web/templates/todo/new.html.eex
<h1>New Todo</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.todo_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.todo_path(@conn, :index) %></span>

lib/todos_web/templates/todo/show.html.eex
<h1>Show Todo</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @todo.title %>
  </li>

  <li>
    <strong>Completed:</strong>
    <%= @todo.completed %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.todo_path(@conn, :edit, @todo) %></span>
<span><%= link "Back", to: Routes.todo_path(@conn, :index) %></span>